package com.gxj.cropyield.modules.report.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;
/**
 * 报表分析模块的数据传输对象（记录类型），在报表分析场景下承载参数与返回值。
 */

public record ReportRequest(
    @NotBlank(message = "报告标题不能为空")
    @Size(max = 128, message = "标题长度不能超过128位")
    String title,

    @Size(max = 512, message = "描述长度不能超过512位")
    String description,

    @Size(max = 128, message = "作者名称不能超过128位")
    String author,

    @Size(max = 128, message = "覆盖周期不能超过128位")
    String coveragePeriod,

    @NotNull(message = "预测结果ID不能为空")
    Long forecastResultId,

    @Size(max = 2048, message = "洞察长度不能超过2048字符")
    String insights,

    @Size(max = 32, message = "状态长度不能超过32位")
    String status,

    LocalDateTime publishedAt,

    Boolean autoGenerated
) {
}
