package com.gxj.cropyield.modules.report.dto;

import java.time.LocalDateTime;
/**
 * 报表分析模块的数据传输对象（记录类型），在报表分析场景下承载参数与返回值。
 */

public record ReportSummaryResponse(
    Long id,
    String title,
    String description,
    String author,
    String coveragePeriod,
    String status,
    boolean autoGenerated,
    LocalDateTime publishedAt,
    String insights
) {
}
