package com.gxj.cropyield.modules.report.dto;

import java.time.LocalDateTime;

public record ReportSummaryResponse(
    Long id,
    String title,
    String description,
    String author,
    String coveragePeriod,
    String status,
    boolean autoGenerated,
    LocalDateTime publishedAt,
    String insights
) {
}
