<template>
  <el-drawer
    :model-value="modelValue"
    size="65%"
    :append-to-body="true"
    :destroy-on-close="false"
    :close-on-click-modal="false"
    @close="handleClose"
    class="report-detail-drawer"
  >
    <template #header>
      <div class="drawer-header">
        <div class="header-title">{{ summaryData?.title || '报告详情' }}</div>
        <div v-if="summaryData" class="header-subtitle">
          <span>{{ summaryData.coveragePeriod || '未设置覆盖范围' }}</span>
          <span v-if="summaryData.author">作者：{{ summaryData.author }}</span>
          <span v-if="summaryData.publishedAt">发布时间：{{ formatDate(summaryData.publishedAt) }}</span>
        </div>
        <div v-if="summaryData" class="header-actions">
          <el-select v-model="exportFormat" size="small" class="export-select">
            <el-option label="PDF" value="pdf" />
            <el-option label="Excel" value="excel" />
          </el-select>
          <el-button type="primary" size="small" :loading="exporting" @click="handleExport">
            导出
          </el-button>
          <el-popconfirm
            v-if="canDelete"
            title="确定要删除这份报告吗？"
            confirm-button-text="确定"
            cancel-button-text="取消"
            @confirm="handleDelete"
          >
            <template #reference>
              <el-button type="danger" size="small">删除</el-button>
            </template>
          </el-popconfirm>
        </div>
      </div>
    </template>

    <el-scrollbar class="drawer-scroll">
      <div class="drawer-body">
        <el-alert v-if="errorMessage" type="error" :closable="false" show-icon class="mb-3">{{ errorMessage }}</el-alert>

        <el-skeleton v-if="loading" animated :rows="6" />
        <template v-else>
          <div v-if="summaryData" class="summary-card">
            <div class="summary-meta">
              <el-tag type="success" size="small" v-if="summaryData.autoGenerated">自动生成</el-tag>
              <el-tag v-else size="small">手动创建</el-tag>
              <el-tag v-if="summaryData.status" size="small" effect="plain">{{ summaryData.status }}</el-tag>
            </div>
            <el-alert
              v-if="summaryData.insights"
              type="info"
              :closable="false"
              show-icon
              class="mt-2"
            >
              {{ summaryData.insights }}
            </el-alert>
          </div>

          <el-empty v-if="!sections.length" description="暂无详细内容" />

          <div v-else class="section-list">
            <el-card v-for="section in sections" :key="section.id || section.title" shadow="hover" class="section-card">
              <template #header>
                <div class="section-header">
                  <div class="section-title">{{ section.title }}</div>
                  <el-tag size="small" effect="plain">{{ formatSectionType(section.type) }}</el-tag>
                </div>
                <p v-if="section.description" class="section-description">{{ section.description }}</p>
              </template>

              <template v-if="section.type === 'OVERVIEW'">
                <div class="metric-grid">
                  <div v-for="metric in section.data?.metrics || []" :key="metric.label" class="metric-item">
                    <div class="metric-label">{{ metric.label }}</div>
                    <div class="metric-value">{{ formatMetric(metric.value, metric.unit) }}</div>
                  </div>
                </div>
                <div v-if="section.data?.highlights?.length" class="highlight-box">
                  <div class="highlight-title">重点洞察</div>
                  <ul>
                    <li v-for="item in section.data.highlights" :key="item">{{ item }}</li>
                  </ul>
                </div>
              </template>

              <template v-else-if="section.type === 'YIELD_TREND'">
                <el-table :data="section.data?.series || []" border size="small" style="width: 100%">
                  <el-table-column prop="year" label="年份" width="90" />
                  <el-table-column
                    prop="sownArea"
                    label="播种面积"
                    :formatter="(_, __, value) => formatNumber(value, { maximumFractionDigits: 2 }) + ' 千公顷'"
                  />
                  <el-table-column
                    prop="production"
                    label="总产量"
                    :formatter="(_, __, value) => formatNumber(value, { maximumFractionDigits: 2 }) + ' 万吨'"
                  />
                  <el-table-column
                    prop="yieldPerHectare"
                    label="单产"
                    :formatter="(_, __, value) => formatNumber(value, { maximumFractionDigits: 2 }) + ' 吨/公顷'"
                  />
                </el-table>
              </template>

              <template v-else-if="section.type === 'FORECAST_COMPARISON'">
                <el-descriptions :column="2" border>
                  <el-descriptions-item label="预测年份">{{ section.data?.forecastYear || '--' }}</el-descriptions-item>
                  <el-descriptions-item :label="forecastMeasurementLabel(section.data)">
                    {{ formatForecastMeasurement(section.data) }}
                  </el-descriptions-item>
                  <el-descriptions-item
                    v-if="section.data?.predictedProduction != null && isYieldMeasurement(section.data)"
                    label="预测总产量"
                  >
                    {{ formatWithUnit(section.data.predictedProduction, '吨') }}
                  </el-descriptions-item>
                  <el-descriptions-item :label="actualMeasurementLabel(section.data)">
                    {{ formatActualMeasurement(section.data) }}
                  </el-descriptions-item>
                  <el-descriptions-item v-if="section.data?.difference != null" label="偏差">
                    {{ formatDifference(section.data) }}
                  </el-descriptions-item>
                  <el-descriptions-item label="模型">{{ section.data?.task?.model || '--' }}</el-descriptions-item>
                  <el-descriptions-item label="模型类型">{{ section.data?.task?.modelType || '--' }}</el-descriptions-item>
                </el-descriptions>
                <p v-if="section.data?.evaluation" class="section-footer">模型评估：{{ section.data.evaluation }}</p>
              </template>

              <template v-else>
                <pre class="raw-json">{{ section.data }}</pre>
              </template>
            </el-card>
          </div>
        </template>
      </div>
    </el-scrollbar>
  </el-drawer>
</template>

<script setup>
import { computed, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { exportReport as exportReportApi, fetchReportDetail } from '../../services/report'

const props = defineProps({
  modelValue: { type: Boolean, default: false },
  reportId: { type: [Number, String], default: null },
  summary: { type: Object, default: null },
  canDelete: { type: Boolean, default: false }
})

const emit = defineEmits(['update:modelValue', 'delete'])

const loading = ref(false)
const errorMessage = ref('')
const detail = ref(null)
const lastLoadedId = ref(null)
const exportFormat = ref('pdf')
const exporting = ref(false)

const summaryData = computed(() => detail.value?.summary ?? props.summary ?? null)
const sections = computed(() => detail.value?.sections ?? [])

const formatDate = value => {
  if (!value) return '--'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) {
    return value
  }
  return date.toLocaleDateString('zh-CN')
}

const formatNumber = (value, options = {}) => {
  if (value === null || value === undefined || value === '') return '--'
  if (typeof value !== 'number') return value
  if (Number.isNaN(value)) return '--'
  const formatter = new Intl.NumberFormat('zh-CN', options)
  return formatter.format(value)
}

const formatMetric = (value, unit) => {
  let numeric = value
  if (typeof numeric !== 'number') {
    numeric = Number(value)
  }
  if (Number.isNaN(numeric)) {
    return '--'
  }
  const formatted = formatNumber(numeric, { maximumFractionDigits: 2 })
  return formatted === '--' ? '--' : unit ? `${formatted} ${unit}` : formatted
}

const formatWithUnit = (value, unit, options = { maximumFractionDigits: 2 }) => {
  const formatted = formatNumber(value, options)
  if (formatted === '--') {
    return '--'
  }
  return unit ? `${formatted} ${unit}` : formatted
}

const isYieldMeasurement = data => {
  if (!data) return false
  if (data.predictedYield != null) return true
  const unit = data.measurementUnit
  const label = data.measurementLabel
  return (
    (typeof unit === 'string' && unit.includes('公顷')) ||
    (typeof label === 'string' && label.includes('单产'))
  )
}

const forecastMeasurementLabel = data => {
  if (!data) return '预测值'
  return data.measurementLabel || (isYieldMeasurement(data) ? '预测单产' : '预测值')
}

const formatForecastMeasurement = data => {
  if (!data) return '--'
  const value = data.measurementValue ?? data.predictedYield ?? null
  const unit = data.measurementUnit || (isYieldMeasurement(data) ? '吨/公顷' : '')
  return formatWithUnit(value, unit)
}

const actualMeasurementLabel = data => (isYieldMeasurement(data) ? '实际单产' : '实际值')

const formatActualMeasurement = data => {
  if (!isYieldMeasurement(data)) {
    return '--'
  }
  if (data?.actualYield != null) {
    return formatWithUnit(data.actualYield, '吨/公顷')
  }
  return '待更新'
}

const formatDifference = data => {
  if (data?.difference == null) {
    return '--'
  }
  const unit = isYieldMeasurement(data) ? '吨/公顷' : data?.measurementUnit || ''
  return formatWithUnit(data.difference, unit)
}

const extractFilename = disposition => {
  if (!disposition) return ''
  const utf8Match = /filename\*=UTF-8''([^;]+)/i.exec(disposition)
  if (utf8Match && utf8Match[1]) {
    return decodeURIComponent(utf8Match[1])
  }
  const filenameMatch = /filename="?([^";]+)"?/i.exec(disposition)
  return filenameMatch ? filenameMatch[1] : ''
}

const handleExport = async () => {
  if (!props.reportId) {
    ElMessage.warning('请选择要导出的报告')
    return
  }
  exporting.value = true
  try {
    const response = await exportReportApi(props.reportId, exportFormat.value)
    const blob = new Blob([response.data], {
      type: response.headers['content-type'] || 'application/octet-stream'
    })
    const filename =
      extractFilename(response.headers['content-disposition']) ||
      `报告导出.${exportFormat.value === 'excel' ? 'xlsx' : 'pdf'}`
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    link.click()
    window.URL.revokeObjectURL(url)
  } catch (error) {
    const message = error?.response?.data?.message || '导出报告失败'
    errorMessage.value = message
    ElMessage.error(message)
  } finally {
    exporting.value = false
  }
}

const formatSectionType = type => {
  switch (type) {
    case 'OVERVIEW':
      return '指标概览'
    case 'YIELD_TREND':
      return '产量趋势'
    case 'FORECAST_COMPARISON':
      return '预测对比'
    default:
      return type || '附录'
  }
}

const fetchDetail = async id => {
  if (!id) {
    detail.value = null
    return
  }
  if (lastLoadedId.value === id && detail.value) {
    return
  }
  loading.value = true
  errorMessage.value = ''
  try {
    const { data } = await fetchReportDetail(id)
    detail.value = data?.data ?? data
    lastLoadedId.value = id
  } catch (error) {
    errorMessage.value = error?.response?.data?.message || '加载报告详情失败'
    detail.value = null
  } finally {
    loading.value = false
  }
}

watch(
  () => props.modelValue,
  value => {
    if (value && props.reportId) {
      fetchDetail(props.reportId)
    }
  }
)

watch(
  () => props.reportId,
  newId => {
    if (props.modelValue && newId) {
      fetchDetail(newId)
    }
  }
)

const handleClose = () => {
  emit('update:modelValue', false)
}

const handleDelete = () => {
  if (!props.reportId) {
    ElMessage.warning('无法删除报告')
    return
  }
  emit('delete', props.reportId)
}
</script>

<style scoped>
.report-detail-drawer :deep(.el-drawer__header) {
  margin-bottom: 0;
}

.report-detail-drawer :deep(.el-drawer__body) {
  padding: 0;
  display: flex;
  flex-direction: column;
}

.drawer-scroll {
  width: 100%;
  padding: 0 24px 24px;
  box-sizing: border-box;
}

.report-detail-drawer :deep(.el-scrollbar__wrap) {
  max-height: calc(100vh - 140px);
  padding-right: 8px;
}

.drawer-header {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.header-title {
  font-size: 20px;
  font-weight: 600;
}

.header-subtitle {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  font-size: 13px;
  color: var(--el-text-color-secondary);
}

.header-actions {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 8px;
}

.export-select {
  width: 120px;
}

.drawer-body {
  display: flex;
  flex-direction: column;
  gap: 16px;
  padding-top: 16px;
}

.summary-card {
  padding: 16px;
  border-radius: 12px;
  background: var(--el-fill-color-light);
  border: 1px solid var(--el-border-color-lighter);
}

.summary-meta {
  display: flex;
  gap: 8px;
}

.mt-2 {
  margin-top: 12px;
}

.section-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.section-card {
  border-radius: 12px;
}

.section-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}

.section-title {
  font-weight: 600;
}

.section-description {
  margin: 6px 0 0;
  font-size: 13px;
  color: var(--el-text-color-secondary);
}

.metric-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
  gap: 12px;
}

.metric-item {
  padding: 12px;
  border-radius: 10px;
  background: var(--el-fill-color-lighter);
}

.metric-label {
  font-size: 13px;
  color: var(--el-text-color-secondary);
}

.metric-value {
  font-size: 18px;
  font-weight: 600;
  margin-top: 4px;
}

.highlight-box {
  margin-top: 16px;
  padding: 12px;
  border-radius: 8px;
  background: rgba(64, 158, 255, 0.08);
}

.highlight-title {
  font-weight: 600;
  margin-bottom: 8px;
}

.highlight-box ul {
  margin: 0;
  padding-left: 18px;
  color: var(--el-text-color-regular);
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.section-footer {
  margin-top: 12px;
  font-size: 13px;
  color: var(--el-text-color-secondary);
}

.raw-json {
  padding: 12px;
  margin: 0;
  background: #1e1e1e;
  color: #f8f8f2;
  border-radius: 8px;
  overflow: auto;
}

.mb-3 {
  margin-bottom: 16px;
}
</style>
